// packages/client/src/views/TodoView.vue
<template>
  <div>
    <div v-if="isFetched && allTodos && allTodos.length">
      <div
        v-for="(todo, ind) in allTodos"
        :key="todo.key"
        :class="{ [$style['line-through']]: todo.completed }"
        @click="() => toggleComplete(todo.key)"
      >
        <span> {{ ind + 1 }}. {{ todo.text }} </span>
      </div>
    </div>
    <div v-if="isFetched && allTodos && !allTodos.length">
      You have not created any Todo yet.
    </div>

    <div>
      <h2>Create new Todo</h2>
      <div>
        <input type="text" v-model="text" />
      </div>
      <button type="submit" @click="onCreate">Create</button>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query";
import { ref } from "vue";
import useTRPC from "../composables/useTRPC";
const { injectTRPC } = useTRPC();
const trpc = injectTRPC();
const queryClient = useQueryClient();

const text = ref<string>("");

const {
  data: allTodos,
  isError,
  error,
  isFetching,
  isFetched,
} = useQuery({
  queryKey: ["todos"],
  queryFn: () => trpc.allTodos.query(),
});

const { mutate: addTodo, isLoading } = useMutation({
  mutationKey: ["add-todo", text],
  mutationFn: () => trpc.addTodo.mutate({ text: text.value }),
  async onSuccess() {
    await queryClient.invalidateQueries({
      queryKey: ["todos"],
    });
  },
});

const { mutate: toggleTodo, isLoading: toggleTodoIsLoading } = useMutation({
  mutationKey: ["toggle-todo-completion"],
  mutationFn: (key: string) => {
    return trpc.toggleTodoCompletion.mutate({ key: key });
  },
  async onSuccess() {
    await queryClient.invalidateQueries({
      queryKey: ["todos"],
    });
  },
});

const onCreate = () => {
  if (text.value.length > 3) {
    addTodo();
  } else {
    alert("Your text is too short.");
  }
};

const toggleComplete = (key: string) => {
  toggleTodo(key);
};
</script>

<style module lang="scss">
.line-through {
  text-decoration: line-through;
}
</style>

// packages/client-react/src/views/TodoView.tsx
import React, { useState } from "react";
import { trpc } from "../utils/trpc";
import styles from "./TodoView.module.scss";

const TodoView = () => {
  const [newTodo, setNewTodo] = useState("");
  const utils = trpc.useContext();

  const {
    data: todos,
    isLoading,
    isError,
    error,
    isFetched,
    fetchStatus,
  } = trpc.allTodos.useQuery();

  const { mutate: addTodo } = trpc.addTodo.useMutation({
    onSuccess() {
      utils.allTodos.invalidate();
    },
  });
  const onCreate = () => {
    if (newTodo && newTodo.length > 3) {
      addTodo({
        text: newTodo,
      });
    } else {
      alert("Your text is too short.");
    }
  };

  const { mutate: toggleTodo } = trpc.toggleTodoCompletion.useMutation({
    onSuccess() {
      utils.allTodos.invalidate();
    },
  });

  const onToggle = (key: string) => {
    toggleTodo({ key });
  };

  return (
    <>
      {isLoading && fetchStatus === "fetching" && <div>Is Loading</div>}
      {isFetched && todos?.length && (
        <div>
          {todos.map((todo, index) => {
            return (
              <div
                className={todo.completed ? styles["line-through"] : ""}
                onClick={() => onToggle(todo.key)}
              >
                <span> {index + 1}. </span>
                <span>{todo.text}</span>
              </div>
            );
          })}
        </div>
      )}
      {isFetched && todos?.length === 0 && (
        <div>You have not created any Todo yet.</div>
      )}
      <div>
        <h2>Create New Todo </h2>
        <div>
          <input
            type="text"
            value={newTodo}
            onInput={(e) => setNewTodo(e.currentTarget.value)}
          />
        </div>
        <button type="submit" onClick={() => onCreate()}>
          Create
        </button>
      </div>
    </>
  );
};

export default TodoView;
